version: '3.8'

services:
  ego:
    build: .
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "8080:8080" # .:default service port
    volumes:
      - .:/usr/src/ego
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432" # .:default postgres port
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
